### ISSUE TITLE
Cannot define custom event structure

### ISSUE THREAD

**Issue by TomKaltz** [adrai/node-cqrs-eventdenormalizer#19]
#18 

I submitted a pull request to show failure in defining custom event structure.  The first failed assertion line 294 is what demonstrates my issue.

**Comment by adrai** [comment]
Really? format 2 tests seams to work correctly (different structure)

**Comment by adrai** [comment]
Perhaps it's just a order problem... Perhaps I'm going to order the viewBuilders and eventExtenders in the next release

**Comment by TomKaltz** [comment]
I'm just really having a hard time getting this event structure to work between domain and denormalizer.  I think I've narrowed it down to denormalizer.  Can you point me in correct direction to make this event structure work?

**Comment by TomKaltz** [comment]
I am not able to get this to work on my end.  It was not working before or I made a typo somewhere.

**Comment by adrai** [comment]
https://github.com/adrai/node-cqrs-eventdenormalizer/blob/master/test/integration/integrationTest.js#L1287
