### ISSUE TITLE
viewbuilder for multiple events

### ISSUE THREAD

**Issue by TomKaltz** [adrai/node-cqrs-eventdenormalizer#24]
```javascript
ed.defineViewBuilder({
    name: '', // optional, default is file name without extension, if name is '' it will handle all events that matches
    aggregate: 'timesheet', // optional
    context: 'timesheet',
    id: 'aggregateId', // if not defined or not found it will generate a new viewmodel with new id
    //payload: 'payload' // optional,
    //if not defined it will pass the whole event...
    autoCreate: true

    // optional, if not defined it will pass the whole event...
    //payload: 'payload'
  },...
```

I have tried this but the denormalizer wouldn't fire for all aggregates named timesheet.  Did I misinterpret "```it will handle all events that matches```"?

**Comment by adrai** [comment]
No, viewBuilders are dedicated to a specific event...

**Comment by TomKaltz** [comment]
What is...

name: '', // optional, default is file name without extension, if name is '' it will handle all events that matches

**Comment by adrai** [comment]
I think this is a mistake... only eventExtenders can do such things...

**Comment by adrai** [comment]
But this could be the next feature ;-)

**Comment by adrai** [comment]
It's ok for you if I do this tomorrow?

**Comment by TomKaltz** [comment]
You can do it whenever you want.  I make no demands for open source
software.  Thanks for your contribution to the community!

**Comment by adrai** [comment]
v1.8.4
