### ISSUE TITLE
need more info on eventExtenders 

### ISSUE THREAD

**Issue by pawarvijay** [adrai/node-cqrs-eventdenormalizer#47]
:) need more understanding on below points related eventExtenders

1 : Though there is viewBuilder, what is actual purpose of eventExtenders.
2 : Do we have to use both or use eventExtenders when we want to extend event.
3 : What kind of things can fit inside eventExtenders.

**Comment by adrai** [comment]
have a look at: https://github.com/adrai/node-cqrs-eventdenormalizer/tree/master/test/integration/fixture/set1

viewBuilders modifies your readmodel
eventExtenders extends an event
