### ISSUE TITLE
viewbuilders not ordering properly

### ISSUE THREAD

**Issue by pawarvijay** [adrai/node-cqrs-eventdenormalizer#48]
hie :)

_**what i am trying to achieve**_ :  i create **sales invoice** and **related to** sales invoice i create **accounting entries** and if there is **problem** in creating accounting entries then i want to cancel sales invoice created earlier.

on **salesInvoiceCreated** event  
  1.  salesInvoiceCreated viewbuilder executes and creates readmodel
  2.  salesInvoiceCreatedSaga.js listens and creates command createAccounting.
  3. i forcefully generated [error in businessrule](https://github.com/pawarvijay/sample-with-context-and-saga-implemented/blob/master/domain/lib/sales/accounting/businessRules/businessRule.js#l4) of createAccounting so that it will throw rejectedCommand event
  4. on rejectedCommand event it will fire [cancelSalesInvoice](https://github.com/pawarvijay/sample-with-context-and-saga-implemented/blob/master/host/viewBuilders/salesinvoice/salesInvoiceDeleted.js#l18) 

[my sample with context and saga implemented
](https://github.com/pawarvijay/sample-with-context-and-saga-implemented)

**_problem_**:
some times every thing works fine it creates sales invoice then and on problem in creating accounting entries it cancels sales invoice created earlier and keeps giving AlreadyDenormalizedError error
**but but but**
some times **cancel sales invoice** fires first and then **create sales invoice** and keeps giving **AlreadyDenormalizedError** error

_**solutions that i tried**_ : 
also i tried to set priority in viewbuilder

**Comment by adrai** [comment]
priority in viewbuilder only guaranties order for same event on multiple viewBuilders

what you need is having just 1 aggregate that generates these events, or try to use the "retry" function in the viewbuilder

**Comment by pawarvijay** [comment]
your module works properly
actually problem was : [if PostgreSQL make update faster, update will return result before insert](https://github.com/brianc/node-postgres/issues/958)
