### ISSUE TITLE
[Question] What are Notification used for?

### ISSUE THREAD

**Issue by AlexandreRoba** [adrai/node-cqrs-eventdenormalizer#51]
Hello,

I'm trying to figure out what are notifications used for? Can someone share is knowledge on the topic please? thanks for any info you could provide on this.

Alex

**Comment by adrai** [comment]
A notification is a change to a viewmodel, it contains always the whole new state of the vm.
This is helpful for tests, and if you want to send the actualized viewmodel to a user (i.e. via socket.io)

**Comment by AlexandreRoba** [comment]
thanks for the clarification.
