### ISSUE TITLE
Dealing with missed events

### ISSUE THREAD

**Issue by nanov** [adrai/node-cqrs-eventdenormalizer#55]
What is the recommended way to deal with missed events?
I tried doing an RPC queue requesting those ( aggId, guardedRev, aggregateRev ) and the handling those one by one, but this approach seems to bring some problems with it ( mainly because of the handle inside handle ). Should i just send the missing events again thought the normal events queue ( send/receiver ) ?

**Comment by adrai** [comment]
Does this help? https://github.com/adrai/node-eventstore/issues/104

**Comment by nanov** [comment]
Well, I had already read those issues and proceeded in  a similar manner.
Actually my "problem" is simpler then i thought, what should be requested from the EventStore is guardedRevision-1 and aggregateRevision-1 from the info object.
Then I process those one by one with the normal handle method ( as I make use of event extenders and preExtenders ), when done in this way everything seems to work as expected.

Is there any particular reason to call only the viewbuilders when replaying events? I am asking because I am thinking about adding it as an option.

**Comment by adrai** [comment]
Short answer: 
When replaying, only the readmodel should be rebuild...
I.e. If you call another service during evtExtenders this should not be called again when rebuilding... -> you can't force everyone to handle rebuilts...

**Comment by nanov** [comment]
I see, it does makes sense, what about adding an option to the (pre)event extender to be replied?

**Comment by adrai** [comment]
should already => or not? https://github.com/adrai/node-cqrs-eventdenormalizer/blob/master/lib/replayHandler.js#L195

**Comment by nanov** [comment]
My bad, it absolutely does!
