### ISSUE TITLE
replayStreamed not committing into the database 

### ISSUE THREAD

**Issue by alemhnan** [adrai/node-cqrs-eventdenormalizer#63]
I'm running the `replayStreamed` function and I have issues in getting it working. Apparently, the `viewBuilders` are not committing the data during each replay. Therefore if to denormalize event `2` I need to lookup data already denormalized in event `1` it fails because it is not committed yet in the database. 

Am I doing something obviously wrong? or maybe you are caching the views and committing in batches?  

 Do you have any hint how to approach this case?

**Comment by adrai** [comment]
Do you have a unit test to reproduce it?

**Comment by alemhnan** [comment]
Not yet. Monday morning I'll isolate the behaviour and publish in a repo. I'll keep you posted.

**Comment by alemhnan** [comment]
Hello, 

I created a repo (https://github.com/alemhnan/UT) that reproduce my issues. There are two commands with one event each. 

On ```npm start``` the two commands will be issued. Then the reply will be run. If you try you will see an error in console. 

It does connect to a mongodb, default set as: `mongodb://localhost:27017/eventstore` and `mongodb://localhost:27017/denormalize`

**Comment by alemhnan** [comment]
That did the trick. Thanks a lot!
