### ISSUE TITLE
how to trigger multiple ViewBuilders for a single event

### ISSUE THREAD

**Issue by alemhnan** [adrai/node-cqrs-eventdenormalizer#64]
I'm trying to define two ViewBuilders in different collections triggered by the same event. It seems that only one is going to be triggered. 

Is it possible?

**Comment by adrai** [comment]
no... this should be possible...
i.e. look at:
https://github.com/adrai/node-cqrs-eventdenormalizer/blob/master/test/integration/fixture/set1/personDetail/viewBuilders/enteredNewPerson.js
https://github.com/adrai/node-cqrs-eventdenormalizer/blob/master/test/integration/fixture/set1/person/viewBuilders/enteredNewPerson.js

**Comment by alemhnan** [comment]
Thanks for the prompt answer and the links.
I'll dive more into that, most likely I'm doing some silly mistake.

**Comment by alemhnan** [comment]
It's working, just some minor error on the definition of the Viewbuilders on my side
