### ISSUE TITLE
Wrong ViewBuilder triggered 

### ISSUE THREAD

**Issue by alemhnan** [adrai/node-cqrs-eventdenormalizer#66]
I am triggering the event 'A'.'B'.'C'. (context.aggregate.event) and the ViewBuilder 'A'.'B'.'C' get correctly triggered.

But also the ViewBuilder D.E.C. ('C' is the same string but context and aggregate different).
I'm fully specifying the ViewBuilders  with name/aggregate/context in the definition like you showed me [here](https://github.com/adrai/node-cqrs-eventdenormalizer/blob/master/test/integration/fixture/set1/personDetail/viewBuilders/enteredNewPerson.js) .

I tried different name for the file with the same results. I also tried to put unrelated random names just to uncouple the definition from the name of the file. 

Do you have any hints? Might it be a bug?

**Comment by adrai** [comment]
Have you defined the context and aggregate path here?
https://github.com/adrai/node-cqrs-eventdenormalizer#define-the-event-structure

**Comment by alemhnan** [comment]
No, or better, I did but not completely. Going to try right now, thanks again for the prompt answer.

**Comment by alemhnan** [comment]
That was it. Awesome. Thanks again.
