### ISSUE TITLE
No occurredAt field in THE_LAST_SEEN_EVENT

### ISSUE THREAD

**Issue by blissi** [adrai/node-cqrs-eventdenormalizer#67]
Hi Adriano,
there is currently no occurredAt-field in the last seen event in the revision-collection.
I couldn't find this string in the codebase, too - have you removed it at some time?

**Comment by adrai** [comment]
no, but probably all of your events will not have it...
It's (optionally) set in the domain

**Comment by adrai** [comment]
You have to configure the commitStamp in the event definition

**Comment by adrai** [comment]
{
  "correlationId": "correlationId",
  "id": "id",
  "name": "name",
  "aggregateId": "aggregate.id",
  "context": "context.name",
  "aggregate": "aggregate.name",
  "payload": "payload",
  "revision": "aggregate.revision",
  "version": "version",
  "meta": "meta",
  "commitStamp": "occurredAt"
}

**Comment by blissi** [comment]
Perfect, thanks for the quick reply!
Haven't seen this option.
