### ISSUE TITLE
How to use 'meta' in `defineViewBuilder`

### ISSUE THREAD

**Issue by alemhnan** [adrai/node-cqrs-eventdenormalizer#69]
I can set the 'meta' field in the `defineEvent' and I would like to subsequently use that value in a viewBuilder.

Is there a way to achieve that? The function being passed as only 'data', the `viewModel` and eventully the callback.

If I do not define explicitly the payload field I do get the whole event with the sub fields 'data' and 'meta' but it would be nice to access the 'meta' field directly.

**Comment by adrai** [comment]
not possible...
you need to handle the whole event
