### ISSUE TITLE
Reconnect if connect fails?

### ISSUE THREAD

**Issue by blissi** [adrai/node-cqrs-eventdenormalizer#72]
Hallo,
I'm using MongoDB. When Mongo is not started and I try to init the event store, it throws an exception:
```
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
```
Question 1: is there a way to instruct cqrs-eventdenormalizer to perform a retry? Same question goes to cqrs-domain.

Question 2: what about retries if the connection is initially fine and the event denormalizer starts up properly. Later Mongo goes down - how should I handle that situation?

Thanks,
Steven

**Comment by adrai** [comment]
In all project I used these cqrs modules, I always killed the whole microservice when the connection to the database is interrupted...

But you should be able i.e. to pass the option: auto_reconnect: true for mongodb if you want to reconnect

**Comment by blissi** [comment]
Ok, so in your experience it is better to restart the microservice?

**Comment by adrai** [comment]
yes

**Comment by blissi** [comment]
Ok thanks.
