### ISSUE TITLE
Update multiple viewmodels question

### ISSUE THREAD

**Issue by ssipos90** [adrai/node-cqrs-eventdenormalizer#83]
Hi,

I am implementing a tree structure based on nested set and when adding a node in the tree, some other nodes need updates.
What I have in mind is handling the domain event in 2 view builders, one adding the node and one updating the other nodes but the problem is I can't specify in the query attribute of the viewBuilder the ID of the tree for example.

```js
module.exports = require('cqrs-eventdenormalizer') .defineViewBuilder(
    {
      name: 'nodeAdded',
      aggregate: 'node',
      context: 'nodes',
      version: 0,
      query: {
          // here
      },
      autoCreate: false,
      priority: 1
    },
    function(data, vm, cb) {
        // ...
    });
```

On my mind only using a function for the query attribute would do the trick.
```js
...
query: function (ev /*, cb */) {
    return {
        treeId: ev.aggregate.id // in my case the domain aggregate is the tree
    }
},
...
```

**Comment by adrai** [comment]
There is a useAsQuery function, see readme

**Comment by ssipos90** [comment]
Haven't read all the comments in the readme (talk about RTFM...).

Thanks!
